refactor: sort active proposals by DAO and expiration
hypha-dao/hypha-wallet pull request #301
Opened 2024-09-04 17:33 UTC by Zied-Dahmani

## Scope

[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/300)

I have implemented the logic to `sort` active proposals by `DAO name` and `expiration` date.

2024-09-05 14:14 UTC, n13 commented on lib/core/extension/proposal_model_extensions.dart
> +      return 'Expired';
Not sure this is the best term - is this UX visible?

It should be the same as on the web... maybe passed of failed?

2024-09-05 14:15 UTC, n13 commented on lib/core/network/repository/proposal_repository.dart
> +
if we have the concept that a proposal can be expired then that should be handled in a utility function so we don't repeat this code everywhere (isBefore(now))

2024-09-05 14:15 UTC, n13 commented on lib/core/network/repository/proposal_repository.dart
> +
I recommend an extension on ProposalModel "isExpired"

2024-09-05 14:16 UTC, n13 requested changes
refactor so isExpired code is only in 1 place (see comments)

2024-09-05 17:59 UTC, Zied-Dahmani commented
> refactor so isExpired code is only in 1 place (see comments)

You are absolutely right about the comments. However, I’m marking this as a 'to-do' item (which is why I haven’t implemented it as an extension yet). I believe that active proposals should not include expired ones.

2024-09-06 04:53 UTC, n13 approved these changes
Ok - refactor the isExpired fucntion is a To-Do item

2024-09-06 04:53 UTC, n13 approved these changes
I see changes were made. 

LGTM!

2024-09-06 10:05 UTC, merged