feat: Implement the calculation of tokens amounts
hypha-dao/hypha-wallet pull request #331
Opened 2024-09-26 23:11 UTC by nbetsaif

Implemented dynamic token amount updates based on the toggle switch to calculate the token amount per period or for one cycle, ensuring proper handling of cases where no tokens are available. When tokens are absent, the toggle switch and token-related UI elements are hidden to enhance the user experience by only displaying relevant information.

## Screenshots
PerPeriod            |  For1Cycle
:-------------------------:|:-------------------------:
![PerPeriod](https://github.com/user-attachments/assets/11d06884-c30c-4686-8c44-ace9a85b5ab4)  |  ![For1Cycle](https://github.com/user-attachments/assets/31c2e97a-f714-452e-a28f-de812376dc66)

2024-09-27 03:08 UTC, n13 commented on lib/ui/proposals/details/components/proposal_details_view.dart
> +    bool? isShown) {
isShown is kind of the wrong name for this parameter

All of this is really funky, I would refactor it with these objectives

1 - Make it clear what is happening and why

2 - Make the calculations explicit and clear, numbers should be calculated with numbers and only converted to strings at display time, by number formatters. 

3 - If there's different types involved, use enums, not plain strings based on UX text.

2024-09-27 03:17 UTC, n13 requested changes
I suggest to refactor the calculation completely

Also cycle is the "larger" value 

1 cycle == 4 periods, as in the web interface

1 cycle = 4 weeks for example

1 cycle = 30 days = 1 moon cycle, 1 period = 1/4 cycle

2024-09-27 03:17 UTC, n13 commented on lib/ui/proposals/details/components/proposal_details_view.dart
> +      amount = proposalDetailsModel.tokenValue(0, isShown!);
tokenValue method should use an enum parameter, also _buildTokenRown should use the same enum

2024-09-27 03:17 UTC, n13 commented on lib/core/extension/proposal_details_model_extension.dart
> -    String input;
the model should store all values as numbers

if the values are strings, that's ok, just use accessors to access the number values

there shouldn't be any regexps anywhere here... ??!

2024-09-27 03:35 UTC, n13 commented
Please use these accessors to conver the asset values into doubles - I added computed values to ProposalModelDetails

https://github.com/hypha-dao/hypha-wallet/pull/332

2024-09-29 00:49 UTC, n13 approved these changes
Looking good now

I wonder if cycle duration also comes with settings? 

I saw you're getting period seconds from settings now... maybe cycle seconds are there too? Would be more accurate. 

Once we start testing we need to compare the amounts with the web to make sure it's the same.

2024-09-30 08:32 UTC, nbetsaif commented
@n13 cycle duration doesn't exist in the settings. I followed the web implementation, and they set its value statically as i did on the mobile

2024-09-30 08:32 UTC, merged