feat: implement proposal review page
hypha-dao/hypha-wallet pull request #346
Opened 2024-10-09 13:40 UTC by Zied-Dahmani

## Scope

[Ticket](https://github.com/hypha-dao/hypha-wallet/issues/345)

I have implemented the `proposal creation (review and publish)` page UI.

## Screenshots
<img src="https://github.com/user-attachments/assets/11c2019b-7511-4612-a306-707d0696e53" alt="" width="200">

2024-10-10 13:28 UTC, n13 requested changes
Just some questions - what are the view indices, and can they have names, or an enum instead? So we don't have magic numbers in the code?

2024-10-10 13:47 UTC, Zied-Dahmani commented on lib/ui/proposals/components/proposal_header.dart
I have no idea what the Marketing Circle is, so we let it default, created a ticket, and will get back to it later (I remember Luigi said we would remove it).

2024-10-10 13:50 UTC, Zied-Dahmani commented on lib/ui/proposals/creation/interactor/proposal_creation_bloc.dart
> +          navigate(emit, event.nextViewIndex);
nextViewIndex*, because animateToPage uses an integer for the page index.

2024-10-10 13:51 UTC, Zied-Dahmani commented on lib/ui/proposals/creation/proposal_creation_page.dart
> +      // TODO(Zied-Saif): add other conditions
I didn't understand your question.

2024-10-10 15:18 UTC, n13 commented on lib/ui/proposals/creation/interactor/proposal_creation_bloc.dart
> +          navigate(emit, event.nextViewIndex);
Ok

2024-10-10 15:18 UTC, n13 commented on lib/ui/proposals/components/proposal_header.dart
Ok please make the default "" empty string then.

2024-10-10 15:19 UTC, n13 commented on lib/ui/proposals/components/proposal_header.dart
I don't think it's OK to merge something that is clearly wrong. Principle. Just like we don't merge bugs.

2024-10-10 15:20 UTC, n13 commented on lib/ui/proposals/components/proposal_header.dart
Empty string should be fine as default - some proposals will have a circle some won't (default is no circle)

2024-10-11 06:23 UTC, n13 approved these changes

2024-10-11 08:23 UTC, merged